version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: teste-postgres-db
    environment:
      POSTGRES_DB: teste_backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres123@db:5432/teste_backend_db?schema=workspace
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: yarn start:prod

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000

volumes:
  postgres_data:
